export const ADD_CONTRIBUTOR = "forms/ADD_CONTRIBUTOR";

export const REMOVE_CONTRIBUTOR = "forms/REMOVE_CONTRIBUTOR";

export const SAVE_ARTICLE_DATA = "forms/SAVE_ARTICLE_DATA";

export const CREATE_ARTICLE = "forms/CREATE_ARTICLE";

export const CREATE_SECTION_REQUESTED = "forms/CREATE_SECTION_REQUESTED";

export const CREATE_SECTION_SUCCEEDED = 'forms/CREATE_SECTION_SUCCEEDED';

export const CREATE_SECTION_FAILED = 'forms/CREATE_SECTION_FAILED';