export const ADD_CONTRIBUTOR = "forms/ADD_CONTRIBUTOR";

export const REMOVE_CONTRIBUTOR = "forms/REMOVE_CONTRIBUTOR";

export const SAVE_ARTICLE_FORM_DATA = "forms/SAVE_ARTICLE_FORM_DATA";

export const CLEAR_ARTICLE_FORM_DATA = "forms/CLEAR_ARTICLE_FORM_DATA";

export const CREATE_ARTICLE_REQUESTED = "forms/CREATE_ARTICLE_REQUESTED";

export const CREATE_ARTICLE_SUCCEEDED = 'forms/CREATE_ARTICLE_SUCCEEDED';

export const CREATE_ARTICLE_FAILED = 'forms/CREATE_ARTICLE_FAILED';

export const CREATE_SECTION_REQUESTED = "forms/CREATE_SECTION_REQUESTED";

export const CREATE_SECTION_SUCCEEDED = 'forms/CREATE_SECTION_SUCCEEDED';

export const CREATE_SECTION_FAILED = 'forms/CREATE_SECTION_FAILED';

export const CREATE_AUTHORSHIPS_REQUESTED = "forms/CREATE_AUTHORSHIPS_REQUESTED";

export const CREATE_AUTHORSHIPS_SUCCEEDED = 'forms/CREATE_AUTHORSHIPS_SUCCEEDED';

export const CREATE_AUTHORSHIPS_FAILED = 'forms/CREATE_AUTHORSHIPS_FAILED';
