export const ADD_CONTRIBUTOR_TO_CREATE_ARTICLE_FORM =
  "forms/ADD_CONTRIBUTOR_TO_CREATE_ARTICLE_FORM";

export const REMOVE_CONTRIBUTOR_FROM_CREATE_ARTICLE_FORM =
  "forms/REMOVE_CONTRIBUTOR_FROM_CREATE_ARTICLE_FORM";

export const PUSH_ARTICLE_ON_EDIT_STACK = "forms/PUSH_ARTICLE_ON_EDIT_STACK";
export const POP_ARTICLE_OFF_EDIT_STACK = "forms/POP_ARTICLE_OFF_EDIT_STACK";

export const THROW_ARTICLE_FORM_ERROR = "forms/THROW_ARTICLE_FORM_ERROR";
export const CLEAR_ARTICLE_FORM_ERROR = "forms/CLEAR_ARTICLE_FORM_ERROR";

export const SAVE_ARTICLE_FORM_DATA = "forms/THROW_ARTICLE_FORM_DATA";
export const CLEAR_ARTICLE_FORM_DATA = "forms/CLEAR_ARTICLE_FORM_DATA";

export const CREATE_ARTICLE_REQUESTED = "forms/CREATE_ARTICLE_REQUESTED";
export const CREATE_ARTICLE_SUCCEEDED = 'forms/CREATE_ARTICLE_SUCCEEDED';
export const CREATE_ARTICLE_FAILED = 'forms/CREATE_ARTICLE_FAILED';

export const CREATE_SECTION_REQUESTED = "forms/CREATE_SECTION_REQUESTED";
export const CREATE_SECTION_SUCCEEDED = 'forms/CREATE_SECTION_SUCCEEDED';
export const CREATE_SECTION_FAILED = 'forms/CREATE_SECTION_FAILED';

export const CREATE_AUTHORSHIPS_REQUESTED = "forms/CREATE_AUTHORSHIPS_REQUESTED";
export const CREATE_AUTHORSHIPS_SUCCEEDED = 'forms/CREATE_AUTHORSHIPS_SUCCEEDED';
export const CREATE_AUTHORSHIPS_FAILED = 'forms/CREATE_AUTHORSHIPS_FAILED';
