export const FETCH_SECTIONS_REQUESTED = "forms/FETCH_SECTIONS_REQUESTED";
export const FETCH_SECTIONS_SUCCEEDED = 'forms/FETCH_SECTIONS_SUCCEEDED';
export const FETCH_SECTIONS_FAILED = 'forms/FETCH_SECTIONS_FAILED';

export const CREATE_SECTION_REQUESTED = "forms/CREATE_SECTION_REQUESTED";
export const CREATE_SECTION_SUCCEEDED = 'forms/CREATE_SECTION_SUCCEEDED';
export const CREATE_SECTION_FAILED = 'forms/CREATE_SECTION_FAILED';