export const FETCH_SECTIONS_REQUESTED = "sections/FETCH_SECTIONS_REQUESTED";
export const FETCH_SECTIONS_SUCCEEDED = 'sections/FETCH_SECTIONS_SUCCEEDED';
export const FETCH_SECTIONS_FAILED = 'sections/FETCH_SECTIONS_FAILED';

export const CREATE_SECTION_REQUESTED = "sections/CREATE_SECTION_REQUESTED";
export const CREATE_SECTION_SUCCEEDED = 'sections/CREATE_SECTION_SUCCEEDED';
export const CREATE_SECTION_FAILED = 'sections/CREATE_SECTION_FAILED';

export const DELETE_SECTIONS_REQUESTED = "sections/DELETE_SECTIONS_REQUESTED";
export const DELETE_SECTIONS_SUCCEEDED = 'sections/DELETE_SECTIONS_SUCCEEDED';
export const DELETE_SECTIONS_FAILED = 'sections/DELETE_SECTIONS_FAILED'

export const SET_SELECTED_SECTIONS = "sections/SET_SELECTED_SECTIONS";