export const FETCH_SECTIONS_REQUESTED = "forms/FETCH_SECTIONS_REQUESTED";

export const FETCH_SECTIONS_SUCCEEDED = 'forms/FETCH_SECTIONS_SUCCEEDED';

export const FETCH_SECTIONS_FAILED = 'forms/FETCH_SECTIONS_FAILED';