export const CREATE_ARTICLE = 'core/CREATE_ARTICLE'
export const SAVE_SELECTED_ARTICLES = 'core/SAVE_SELECTED_ARTICLES'
export const FETCH_ARTICLES_REQUESTED = "forms/FETCH_ARTICLES_REQUESTED";
export const FETCH_ARTICLES_SUCCEEDED = 'forms/FETCH_ARTICLES_SUCCEEDED';
export const FETCH_ARTICLES_FAILED = 'forms/FETCH_ARTICLES_FAILED'
export const DELETE_ARTICLES_REQUESTED = "forms/DELETE_ARTICLES_REQUESTED";
export const DELETE_ARTICLES_SUCCEEDED = 'forms/DELETE_ARTICLES_SUCCEEDED';
export const DELETE_ARTICLES_FAILED = 'forms/DELETE_ARTICLES_FAILED'
