export const SET_SELECTED_ARTICLES = 'articles/SET_SELECTED_ARTICLES'
export const FETCH_ARTICLES_REQUESTED = "articles/FETCH_ARTICLES_REQUESTED";
export const FETCH_ARTICLES_SUCCEEDED = 'articles/FETCH_ARTICLES_SUCCEEDED';
export const FETCH_ARTICLES_FAILED = 'articles/FETCH_ARTICLES_FAILED'
export const DELETE_ARTICLES_REQUESTED = "articles/DELETE_ARTICLES_REQUESTED";
export const DELETE_ARTICLES_SUCCEEDED = 'articles/DELETE_ARTICLES_SUCCEEDED';
export const DELETE_ARTICLES_FAILED = 'articles/DELETE_ARTICLES_FAILED'
export const CREATE_ARTICLE_REQUESTED = "articles/CREATE_ARTICLE_REQUESTED";
export const CREATE_ARTICLE_SUCCEEDED = 'articles/CREATE_ARTICLE_SUCCEEDED';
export const CREATE_ARTICLE_FAILED = 'articles/CREATE_ARTICLE_FAILED';

export const CREATE_ARTICLE_FORM = {
  ADD_CONTRIBUTOR:
    "articles/create/ADD_CONTRIBUTOR",
  REMOVE_CONTRIBUTOR:
    "articles/create/REMOVE_CONTRIBUTOR",
  THROW_ERROR:
    "articles/create/THROW_ERROR",
  CLEAR_ERROR:
    "articles/create/CLEAR_ERROR",
  SAVE_FORM_DATA:
    "articles/create/THROW_FORM_DATA",
  CLEAR_FORM_DATA:
    "articles/create/CLEAR_FORM_DATA",
}

export const EDIT_ARTICLE_FORM = {
  PUSH_ARTICLE_ON_STACK: "articles/PUSH_ARTICLE_ON_STACK",
  POP_ARTICLE_OFF_STACK: "articles/POP_ARTICLE_OFF_STACK",
};


