/**
 * Created by nicholas on 8/4/17.
 */
export const FETCH_AUTHORSHIPS_REQUESTED = "forms/FETCH_AUTHORSHIPS_REQUESTED";
export const FETCH_AUTHORSHIPS_SUCCEEDED = "forms/FETCH_AUTHORSHIPS_SUCCEEDED";
export const FETCH_AUTHORSHIPS_FAILED = "forms/FETCH_AUTHORSHIPS_FAILED";

export const CREATE_AUTHORSHIPS_REQUESTED =
  "forms/CREATE_AUTHORSHIPS_REQUESTED";
export const CREATE_AUTHORSHIPS_SUCCEEDED =
  "forms/CREATE_AUTHORSHIPS_SUCCEEDED";
export const CREATE_AUTHORSHIPS_FAILED = "forms/CREATE_AUTHORSHIPS_FAILED";
